export const navItems = [{ name: 'Home', url: '#' }, { name: 'Skills', url: '#skills' }, { name: 'Projects', url: '#projects' }];

export const projects = [
    {
        id: 0,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 1,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 2,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 3,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 4,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 5,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 6,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 7,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 8,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 9,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 10,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 11,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 12,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 13,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 14,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 15,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 16,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
    {
        id: 17,
        image: 'https://e1.pxfuel.com/desktop-wallpaper/526/1000/desktop-wallpaper-roronoa-zoro-wano-zoro-wano.jpg',
        label: 'Best project',
        github: '',
        url: '',
    },
];